/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Products } from '../../models/products';

export interface AddProducts$Params {
      body: Products
}

export function addProducts(http: HttpClient, rootUrl: string, params: AddProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<Products>> {
  const rb = new RequestBuilder(rootUrl, addProducts.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Products>;
    })
  );
}

addProducts.PATH = '/Products/addProduct';
