/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUnreadNotificationCount } from '../fn/notification-management/get-unread-notification-count';
import { GetUnreadNotificationCount$Params } from '../fn/notification-management/get-unread-notification-count';
import { getUnreadNotifications } from '../fn/notification-management/get-unread-notifications';
import { GetUnreadNotifications$Params } from '../fn/notification-management/get-unread-notifications';
import { markAllAsRead } from '../fn/notification-management/mark-all-as-read';
import { MarkAllAsRead$Params } from '../fn/notification-management/mark-all-as-read';
import { markAsRead } from '../fn/notification-management/mark-as-read';
import { MarkAsRead$Params } from '../fn/notification-management/mark-as-read';
import { Notification } from 'src/app/services/models/notificationE';

@Injectable({ providedIn: 'root' })
export class NotificationManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `markAsRead()` */
  static readonly MarkAsReadPath = '/Notification/markAsRead/{id}';

  /**
   * Mark notification as read
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsRead$Response(params: MarkAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return markAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark notification as read
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAsRead(params: MarkAsRead$Params, context?: HttpContext): Observable<void> {
    return this.markAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `markAllAsRead()` */
  static readonly MarkAllAsReadPath = '/Notification/markAllAsRead';

  /**
   * Mark all notifications as read
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markAllAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAllAsRead$Response(params?: MarkAllAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return markAllAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark all notifications as read
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markAllAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markAllAsRead(params?: MarkAllAsRead$Params, context?: HttpContext): Observable<void> {
    return this.markAllAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getUnreadNotifications()` */
  static readonly GetUnreadNotificationsPath = '/Notification/unread';

  /**
   * Get all unread notifications
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUnreadNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotifications$Response(params?: GetUnreadNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Notification>>> {
    return getUnreadNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all unread notifications
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUnreadNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotifications(params?: GetUnreadNotifications$Params, context?: HttpContext): Observable<Array<Notification>> {
    return this.getUnreadNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Notification>>): Array<Notification> => r.body)
    );
  }

  /** Path part for operation `getUnreadNotificationCount()` */
  static readonly GetUnreadNotificationCountPath = '/Notification/count';

  /**
   * Get unread notification count
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUnreadNotificationCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotificationCount$Response(params?: GetUnreadNotificationCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return getUnreadNotificationCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Get unread notification count
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUnreadNotificationCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotificationCount(params?: GetUnreadNotificationCount$Params, context?: HttpContext): Observable<number> {
    return this.getUnreadNotificationCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
