/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Registration } from '../../models/registration';

export interface AddRegistration$Params {
      body: Registration
}

export function addRegistration(http: HttpClient, rootUrl: string, params: AddRegistration$Params, context?: HttpContext): Observable<StrictHttpResponse<Registration>> {
  const rb = new RequestBuilder(rootUrl, addRegistration.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Registration>;
    })
  );
}

addRegistration.PATH = '/Registration/addRegistration';
