/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Registration } from '../../models/registration';

export interface BulkUpdateRegistrationStatus$Params {
      body: {
[key: string]: 'PENDING' | 'CONFIRMED' | 'CANCELED';
}
}

export function bulkUpdateRegistrationStatus(http: HttpClient, rootUrl: string, params: BulkUpdateRegistrationStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Registration>>> {
  const rb = new RequestBuilder(rootUrl, bulkUpdateRegistrationStatus.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Registration>>;
    })
  );
}

bulkUpdateRegistrationStatus.PATH = '/Registration/bulkUpdateStatus';
