/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Registration } from '../../models/registration';

export interface DisplayByEvent$Params {
  eventId: number;
}

export function displayByEvent(http: HttpClient, rootUrl: string, params: DisplayByEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Registration>>> {
  const rb = new RequestBuilder(rootUrl, displayByEvent.PATH, 'get');
  if (params) {
    rb.path('eventId', params.eventId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Registration>>;
    })
  );
}

displayByEvent.PATH = '/Registration/DisplayByEvent/{eventId}';
