/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Registration } from '../../models/registration';

export interface DisplayRegistration$Params {
  idR: number;
}

export function displayRegistration(http: HttpClient, rootUrl: string, params: DisplayRegistration$Params, context?: HttpContext): Observable<StrictHttpResponse<Registration>> {
  const rb = new RequestBuilder(rootUrl, displayRegistration.PATH, 'get');
  if (params) {
    rb.path('idR', params.idR, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Registration>;
    })
  );
}

displayRegistration.PATH = '/Registration/DisplayRegistration/{idR}';
