/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Products } from '../models/products';
import { CategorieBusiness } from './businessCategory';
export interface Business {
  categorieBusiness: CategorieBusiness;
  description: string;
  idBusiness: number;
  name: string;
  logo: string;
  averageRating: number;
  ratingCount: number;
  instagramPageName: string;
  products?: Array<Products>;

}
export interface CreateBusinessDto {
  name: string;
  description: string;
  categorieBusiness: string;
  logo?: string;
  averageRating: number;
  ratingCount: number;
}
