/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Products } from '../models/products';
import { CategorieBusiness } from './businessCategory';

export interface Business {
  categorieBusiness: CategorieBusiness;
  description: string;
  idBusiness: number;
  name: string;
  logo: string;
  averageRating: number;
  ratingCount: number;
  instagramPageName: string;
  businessPdf?: string;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED';
  products?: Array<Products>;
  user?: { id: string; username: string }; // Optional: Add if backend returns user details
}

export interface CreateBusinessDto {
  name: string;
  description: string;
  categorieBusiness: string;
  logo?: string;
  businessPdf?: string;
  instagramPageName?: string;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED';
  averageRating: number;
  ratingCount: number;
}