/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Event } from '../models/event';
export interface EventWithReservationCount {
  event?: Event;
  reservationCount?: number;
}
