/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
import { Registration } from '../models/registration';
export interface Event {
  date?: string;
  description?: string;
  endTime?: LocalTime;
  history?: string;
  idEvent?: number;
  location?: string;
  numberOfPlaces?: number;
  registrations?: Array<Registration>;
  startTime?: LocalTime;
  status?: 'PLANNED' | 'ONGOING' | 'COMPLETED' | 'CANCELED';
  title?: string;
}
