export interface Notification {
    businessId: number;
    businessName: string;
    message: string;
    ownerId?: string;
    timestamp?: string;
  }
/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

// import { Registration } from '../models/registration';
// export interface Notification {
//   createdAt?: string;
//   idNotification?: number;
//   message?: string;
//   read?: boolean;
//   registration?: Registration;
// }
