/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { React } from '../models/react';
import { Respons } from '../models/respons';
import { User } from '../models/user';
export interface Post {
  content?: string;
  createdAt?: string;
  idp?: number;
  imageUrl?: string;
  reacts?: Array<React>;
  responses?: Array<Respons>;
  tags?: 'FINANCE' | 'MARKETING' | 'JOBOFFER';
  title?: string;
  user?: User;
  validated?: boolean;
  videoUrl?: string;
}
