/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Post } from '../models/post';
import { User } from '../models/user';
export interface React {
  idreact?: number;
  post?: Post;
  type?: 'LIKE' | 'DISLIKE';
  user?: User;
}
