/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  email: string;
  firstName: string;
  lastname?: string;
  image?: string;
  password: string;
  role: string;
  dateOfBirth: string; 
}
