/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Post } from '../models/post';
import { User } from '../models/user';
export interface Respons {
  createdAt?: string;
  id?: number;
  post?: Post;
  respons?: string;
  user?: User;
}
