/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { React } from '../../models/react';
import { ReactRequest } from '../../models/react-request';

export interface AddReact$Params {
      body: ReactRequest
}

export function addReact(http: HttpClient, rootUrl: string, params: AddReact$Params, context?: HttpContext): Observable<StrictHttpResponse<React>> {
  const rb = new RequestBuilder(rootUrl, addReact.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<React>;
    })
  );
}

addReact.PATH = '/api/reacts/add';
