/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { React } from '../../models/react';

export interface GetAllReacts$Params {
}

export function getAllReacts(http: HttpClient, rootUrl: string, params?: GetAllReacts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<React>>> {
  const rb = new RequestBuilder(rootUrl, getAllReacts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<React>>;
    })
  );
}

getAllReacts.PATH = '/api/reacts/all';
