/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Respons } from '../../models/respons';

export interface GetRespons$Params {
  id: number;
}

export function getRespons(http: HttpClient, rootUrl: string, params: GetRespons$Params, context?: HttpContext): Observable<StrictHttpResponse<Respons>> {
  const rb = new RequestBuilder(rootUrl, getRespons.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Respons>;
    })
  );
}

getRespons.PATH = '/respons/displayrespons/{id}';
