/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Respons } from '../../models/respons';

export interface GetAllRespons$Params {
}

export function getAllRespons(http: HttpClient, rootUrl: string, params?: GetAllRespons$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Respons>>> {
  const rb = new RequestBuilder(rootUrl, getAllRespons.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Respons>>;
    })
  );
}

getAllRespons.PATH = '/respons/dispalyallrespons';
