/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Respons } from '../../models/respons';

export interface UpdateRespons$Params {
      body: Respons
}

export function updateRespons(http: HttpClient, rootUrl: string, params: UpdateRespons$Params, context?: HttpContext): Observable<StrictHttpResponse<Respons>> {
  const rb = new RequestBuilder(rootUrl, updateRespons.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Respons>;
    })
  );
}

updateRespons.PATH = '/respons/updaterespons';
