/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { RegistrationManagementService } from './services/registration-management.service';
export { NotificationManagementService } from './services/notification-management.service';
export { EventManagementService } from './services/event-management.service';
export { AuthenticationService } from './services/authentication.service';
